# Generated by Django 6.0.5 on 2026-05-15 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno_tymu', models.CharField(max_length=255)),
                ('pocet_hracu', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Hrac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=255)),
                ('prijmeni', models.CharField(max_length=255)),
                ('pozice', models.CharField(choices=[('Brankář', 'Brankář'), ('Obránce', 'Obránce'), ('Záložník', 'Záložník'), ('Útočník', 'Útočník')], max_length=20)),
                ('tym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hraci', to='turnaj.tym')),
            ],
        ),
        migrations.CreateModel(
            name='Zapas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domaci_goly', models.IntegerField(default=0)),
                ('hoste_goly', models.IntegerField(default=0)),
                ('datum_zapasu', models.DateTimeField()),
                ('domaci_tym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domaci_zapasy', to='turnaj.tym')),
                ('hostujici_tym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostujici_zapasy', to='turnaj.tym')),
            ],
        ),
    ]
