# Generated by Django 5.2.15 on 2026-06-10 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnaj', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zapas',
            old_name='hoste_goly',
            new_name='hostujici_goly',
        ),
        migrations.RemoveField(
            model_name='tym',
            name='pocet_hracu',
        ),
        migrations.AddField(
            model_name='hrac',
            name='goly',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hrac',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hrac',
            name='jmeno',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hrac',
            name='pozice',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hrac',
            name='prijmeni',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tym',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tym',
            name='jmeno_tymu',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='zapas',
            name='datum_zapasu',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='zapas',
            name='domaci_tym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zapas_domaci', to='turnaj.tym'),
        ),
        migrations.AlterField(
            model_name='zapas',
            name='hostujici_tym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zapas_hoste', to='turnaj.tym'),
        ),
        migrations.AlterField(
            model_name='zapas',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
