# Generated by Django 5.2.15 on 2026-06-10 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnaj', '0002_rename_hoste_goly_zapas_hostujici_goly_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zapas',
            old_name='domaci_tym',
            new_name='id_domaci_tym',
        ),
        migrations.RenameField(
            model_name='zapas',
            old_name='hostujici_tym',
            new_name='id_hostujici_tym',
        ),
        migrations.DeleteModel(
            name='Hrac',
        ),
    ]
