# Generated by Django 5.2.15 on 2026-06-10 19:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnaj', '0003_rename_domaci_tym_zapas_id_domaci_tym_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zapas',
            name='domaci_goly',
            field=models.IntegerField(default=-1, validators=[django.core.validators.MinValueValidator(-1)]),
        ),
        migrations.AlterField(
            model_name='zapas',
            name='hostujici_goly',
            field=models.IntegerField(default=-1, validators=[django.core.validators.MinValueValidator(-1)]),
        ),
    ]
