# Generated by Django 5.2.15 on 2026-06-10 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnaj', '0004_alter_zapas_domaci_goly_alter_zapas_hostujici_goly'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hrac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=50)),
                ('prijmeni', models.CharField(max_length=50)),
                ('id_tym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hraci', to='turnaj.tym')),
            ],
        ),
        migrations.CreateModel(
            name='Střelec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pocet_golu', models.PositiveIntegerField(default=1)),
                ('id_hrac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goly_v_zapasech', to='turnaj.hrac')),
                ('id_zapas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strelci', to='turnaj.zapas')),
            ],
        ),
    ]
